name: 'Setup Coding Agent Environment'
description: 'Installs uv and gh CLI.'

runs:
  using: "composite"
  steps:
    - name: Install GitHub CLI
      shell: bash
      run: |
        type -p curl >/dev/null || (sudo apt-get update && sudo apt-get install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt-get update \
        && sudo apt-get install gh -y

    - name: Install uv
      shell: bash
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
