name: 'Setup Agent Environment'
description: 'Sets up the Python environment, installs uv, gh CLI, and agent dependencies.'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.x'

runs:
  using: "composite"
  steps:
    - name: Install GitHub CLI
      shell: bash
      run: |
        type -p curl >/dev/null || (sudo apt-get update && sudo apt-get install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt-get update \
        && sudo apt-get install gh -y

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      shell: bash
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies with uv
      shell: bash
      run: ~/.local/bin/uv pip install -p $(which python) .
      working-directory: agent
