name: 'Run Coding Agent'
description: 'Sets up Python, installs agent dependencies, and runs the coding agent script.'

inputs:
  agent_mode:
    description: 'The mode to run the agent in (draft or revise).'
    required: true
  issue_title:
    description: 'The title of the issue (for draft mode).'
    required: false
  issue_body:
    description: 'The body of the issue (for draft mode).'
    required: false
  pr_number:
    description: 'The pull request number (for revise mode).'
    required: false
  gemini_api_key:
    description: 'The API key for the Gemini service.'
    required: true
  github_token:
    description: 'The GitHub token for CLI authentication (for revise mode).'
    required: false
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.x'
  gemini_model:
    description: 'The Gemini model to use for AI interactions.'
    required: false
    default: 'models/gemini-2.5-flash'
  gemini_rate_limit_per_minute:
    description: 'The rate limit per minute for Gemini API calls. Set to 0 for no limit.'
    required: false
    default: '10'

outputs:
  changed_files:
    description: 'A multi-line string of file paths modified by the agent.'
    value: ${{ steps.run-script.outputs.changed_files }}
  agent_summary_output:
    description: 'The final natural language summary from the agent.'
    value: ${{ steps.run-script.outputs.agent_summary_output }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install agent dependencies with uv
      shell: bash
      run: ~/.local/bin/uv pip install -p $(which python) .
      working-directory: ${{ github.action_path }}

    - name: Run agent script
      id: run-script
      shell: bash
      run: python -m src.main
      working-directory: ${{ github.action_path }}
      env:
        AGENT_MODE: ${{ inputs.agent_mode }}
        ISSUE_TITLE: ${{ inputs.issue_title }}
        ISSUE_BODY: ${{ inputs.issue_body }}
        PR_NUMBER: ${{ inputs.pr_number }}
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        GH_TOKEN: ${{ inputs.github_token }}
        GEMINI_MODEL: ${{ inputs.gemini_model }}
        GEMINI_RATE_LIMIT_PER_MINUTE: ${{ inputs.gemini_rate_limit_per_minute }}
        AGENT_WORKING_DIRECTORY: ${{ github.workspace }}
